-- Generated by: prisma migrate diff --from-empty --to-schema-datamodel prisma/schema.prisma --script
-- citext lives in the Supabase 'extensions' schema.
SET search_path = public, extensions;

-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "public";

-- CreateEnum
CREATE TYPE "PortalType" AS ENUM ('GOVERNMENT', 'BIDDER', 'PLATFORM');

-- CreateEnum
CREATE TYPE "OrgType" AS ENUM ('GOVERNMENT', 'BIDDER', 'PLATFORM');

-- CreateEnum
CREATE TYPE "OrgStatus" AS ENUM ('ACTIVE', 'SUSPENDED');

-- CreateEnum
CREATE TYPE "UserStatus" AS ENUM ('ACTIVE', 'INVITED', 'LOCKED', 'DEACTIVATED');

-- CreateEnum
CREATE TYPE "MembershipStatus" AS ENUM ('ACTIVE', 'REMOVED');

-- CreateEnum
CREATE TYPE "Role" AS ENUM ('ORG_ADMIN', 'BUYER', 'TECHNICAL_EVALUATOR', 'FINANCIAL_EVALUATOR', 'VERIFIER', 'COMMITTEE_MEMBER', 'APPROVING_AUTHORITY', 'AUDITOR', 'BIDDER_ADMIN', 'BID_USER', 'DOCUMENT_MANAGER', 'SYSTEM_ADMIN');

-- CreateEnum
CREATE TYPE "ProcurementMode" AS ENUM ('SINGLE_ENVELOPE', 'TWO_ENVELOPE');

-- CreateEnum
CREATE TYPE "TenderState" AS ENUM ('DRAFT', 'UNDER_REVIEW', 'APPROVED', 'PUBLISHED', 'OPEN_FOR_BIDS', 'BID_CLOSURE', 'TECHNICAL_EVALUATION', 'FINANCIAL_EVALUATION', 'AWARD_DECISION', 'CLOSED', 'CANCELLED');

-- CreateEnum
CREATE TYPE "ReferenceDatePolicy" AS ENUM ('BID_DEADLINE', 'EVALUATION_DATE');

-- CreateEnum
CREATE TYPE "TenderVersionReason" AS ENUM ('ORIGINAL', 'CORRIGENDUM');

-- CreateEnum
CREATE TYPE "TenderDocumentRole" AS ENUM ('MAIN', 'ANNEXURE', 'CORRIGENDUM', 'SCHEDULE', 'OTHER');

-- CreateEnum
CREATE TYPE "RequirementCategory" AS ENUM ('IDENTITY', 'STATUTORY', 'FINANCIAL', 'EXPERIENCE', 'TECHNICAL', 'CERTIFICATION', 'DECLARATION', 'OTHER');

-- CreateEnum
CREATE TYPE "Envelope" AS ENUM ('TECHNICAL', 'FINANCIAL');

-- CreateEnum
CREATE TYPE "RequirementStatus" AS ENUM ('ACTIVE', 'REMOVED');

-- CreateEnum
CREATE TYPE "RuleOrigin" AS ENUM ('AI_GENERATED', 'OFFICER_AUTHORED', 'OFFICER_EDITED', 'CORRIGENDUM', 'SEEDED');

-- CreateEnum
CREATE TYPE "RuleVersionStatus" AS ENUM ('DRAFT', 'AI_EXTRACTED', 'REVIEW_REQUIRED', 'APPROVED', 'ACTIVE', 'REJECTED', 'SUPERSEDED');

-- CreateEnum
CREATE TYPE "CorrigendumState" AS ENUM ('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'PUBLISHED', 'REJECTED');

-- CreateEnum
CREATE TYPE "DocType" AS ENUM ('PAN_CARD', 'GST_CERTIFICATE', 'UDYAM_CERTIFICATE', 'INCORPORATION_CERTIFICATE', 'ITR_ACKNOWLEDGEMENT', 'BALANCE_SHEET', 'PROFIT_AND_LOSS', 'CA_CERTIFICATE_TURNOVER', 'CA_CERTIFICATE_NETWORTH', 'EXPERIENCE_CERTIFICATE', 'WORK_ORDER', 'COMPLETION_CERTIFICATE', 'OEM_AUTHORISATION', 'BIS_CERTIFICATE', 'ISO_CERTIFICATE', 'DECLARATION', 'LOCAL_CONTENT_CERTIFICATE', 'EPFO_REGISTRATION', 'ESIC_REGISTRATION', 'AUTHORISATION_LETTER', 'FINANCIAL_BID', 'TENDER_DOCUMENT', 'CORRIGENDUM', 'VERIFICATION_CAPTURE', 'OTHER');

-- CreateEnum
CREATE TYPE "TextLayer" AS ENUM ('NATIVE', 'OCR', 'MIXED', 'NONE');

-- CreateEnum
CREATE TYPE "DocumentProcessingStatus" AS ENUM ('UPLOADED', 'VALIDATING', 'PROCESSING', 'EXTRACTED', 'REVIEW_REQUIRED', 'FAILED', 'ARCHIVED');

-- CreateEnum
CREATE TYPE "ScanStatus" AS ENUM ('CLEAN', 'INFECTED', 'SKIPPED');

-- CreateEnum
CREATE TYPE "BidState" AS ENUM ('DRAFT', 'READY_FOR_SUBMISSION', 'SUBMITTED', 'TECHNICAL_REVIEW', 'VERIFICATION', 'EVALUATED', 'DECISION', 'CLARIFICATION_REQUIRED', 'WITHDRAWN', 'REJECTED', 'AWARDED', 'UNSUCCESSFUL');

-- CreateEnum
CREATE TYPE "BidSource" AS ENUM ('PORTAL', 'OFFICER_IMPORT');

-- CreateEnum
CREATE TYPE "BidVersionReason" AS ENUM ('SUBMISSION', 'CLARIFICATION', 'WITHDRAWAL');

-- CreateEnum
CREATE TYPE "ExtractionMethod" AS ENUM ('NATIVE_REGEX', 'OCR_REGEX', 'TABLE_PARSE', 'LLM', 'MANUAL');

-- CreateEnum
CREATE TYPE "ClaimStatus" AS ENUM ('DOCUMENT_UPLOADED', 'FIELD_EXTRACTED', 'STRUCTURALLY_VALID', 'DOCUMENT_SUPPORTED', 'RECONCILED', 'AUTHORITATIVE_VERIFIED', 'CONFLICT', 'REVIEW_REQUIRED', 'UNVERIFIABLE', 'EXPIRED', 'REVOKED');

-- CreateEnum
CREATE TYPE "FreshnessState" AS ENUM ('FRESH', 'EXPIRING', 'EXPIRED', 'REVERIFICATION_REQUIRED', 'REVOKED', 'CONFLICTED');

-- CreateEnum
CREATE TYPE "EvidenceRole" AS ENUM ('SUPPORTS', 'CONFLICTS', 'CONTEXT');

-- CreateEnum
CREATE TYPE "ReconciliationOutcome" AS ENUM ('CONSISTENT', 'NORMALISED_MATCH', 'CONFLICT', 'INSUFFICIENT_EVIDENCE');

-- CreateEnum
CREATE TYPE "SourceCode" AS ENUM ('PAN', 'GST', 'UDYAM', 'MCA', 'DIGILOCKER', 'EPFO', 'ESIC', 'BIS', 'PDF_SIGNATURE', 'QR', 'STRUCTURAL', 'CROSS_DOCUMENT', 'GST_PROVIDER_API', 'SIMULATED');

-- CreateEnum
CREATE TYPE "VerificationMethod" AS ENUM ('AUTHORIZED_API', 'PROVIDER_API', 'QR', 'DIGITAL_SIGNATURE', 'ISSUER', 'RECONCILIATION', 'OFFICER_ASSISTED', 'STRUCTURAL', 'SIMULATED');

-- CreateEnum
CREATE TYPE "CapabilityStatus" AS ENUM ('LIVE_VALIDATED', 'INTEGRATION_READY', 'MANUAL_ONLY', 'UNAVAILABLE', 'DISABLED', 'SIMULATED');

-- CreateEnum
CREATE TYPE "CredentialStatus" AS ENUM ('CONFIGURED', 'MISSING', 'INVALID');

-- CreateEnum
CREATE TYPE "VerificationRoute" AS ENUM ('AUTO', 'RECONCILIATION', 'HUMAN', 'UNAVAILABLE');

-- CreateEnum
CREATE TYPE "AutomationState" AS ENUM ('AUTO_AVAILABLE', 'EVIDENCE_RECONCILIATION', 'HUMAN_REQUIRED', 'UNAVAILABLE', 'FAILED', 'VERIFIED', 'CONFLICT', 'EXPIRED');

-- CreateEnum
CREATE TYPE "VerificationTaskStatus" AS ENUM ('QUEUED', 'IN_PROGRESS', 'VERIFIED', 'FAILED', 'UNAVAILABLE', 'CONFLICT', 'EXPIRED', 'REVIEWED');

-- CreateEnum
CREATE TYPE "VerificationOutcome" AS ENUM ('MATCH', 'NO_MATCH', 'NOT_FOUND', 'SOURCE_ERROR', 'SIGNATURE_VALID', 'SIGNATURE_INVALID', 'SIGNATURE_UNTRUSTED', 'DECODED');

-- CreateEnum
CREATE TYPE "RunStatus" AS ENUM ('RUNNING', 'COMPLETE', 'FAILED');

-- CreateEnum
CREATE TYPE "RunTrigger" AS ENUM ('MANUAL', 'SUBMISSION', 'CORRIGENDUM', 'CLARIFICATION', 'VERIFICATION_UPDATE');

-- CreateEnum
CREATE TYPE "ComplianceResult" AS ENUM ('NOT_ASSESSED', 'PENDING_VERIFICATION', 'PASS', 'FAIL', 'REVIEW_REQUIRED', 'NOT_APPLICABLE', 'BLOCKED');

-- CreateEnum
CREATE TYPE "GateStatus" AS ENUM ('PASS', 'FAIL', 'PENDING');

-- CreateEnum
CREATE TYPE "RiskLevel" AS ENUM ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL');

-- CreateEnum
CREATE TYPE "ExceptionCategory" AS ENUM ('MISSING_DOCUMENT', 'IDENTITY_CONFLICT', 'FIELD_CONFLICT', 'FINANCIAL_EVIDENCE_CONFLICT', 'VERIFICATION_PENDING', 'VERIFICATION_FAILED', 'SOURCE_UNAVAILABLE', 'EXPIRED_EVIDENCE', 'LOW_EXTRACTION_CONFIDENCE', 'RULE_AMBIGUITY', 'MANDATORY_GATE_FAILED', 'RELATIONSHIP_SIGNAL', 'DOCUMENT_UNREADABLE', 'INTEGRITY_FAILURE', 'DOCUMENT_TYPE_MISMATCH');

-- CreateEnum
CREATE TYPE "ExceptionStatus" AS ENUM ('OPEN', 'ASSIGNED', 'IN_REVIEW', 'CLARIFICATION_REQUESTED', 'RESOLVED', 'ESCALATED', 'REOPENED');

-- CreateEnum
CREATE TYPE "DecisionAction" AS ENUM ('TECHNICALLY_COMPLIANT', 'TECHNICALLY_NON_COMPLIANT', 'NEEDS_CLARIFICATION', 'REFER_TO_COMMITTEE', 'FINAL_DECISION');

-- CreateEnum
CREATE TYPE "ClarificationStatus" AS ENUM ('OPEN', 'RESPONDED', 'CLOSED', 'EXPIRED');

-- CreateEnum
CREATE TYPE "JobStatus" AS ENUM ('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'DEAD');

-- CreateEnum
CREATE TYPE "ReportType" AS ENUM ('BID_COMPLIANCE', 'TENDER_PACKAGE', 'EXCEPTIONS', 'VERIFICATION', 'AUDIT');

-- CreateEnum
CREATE TYPE "ReportFormat" AS ENUM ('PDF', 'CSV', 'JSON');

-- CreateTable
CREATE TABLE "organisations" (
    "id" UUID NOT NULL,
    "code" TEXT NOT NULL,
    "type" "OrgType" NOT NULL,
    "legal_name" TEXT NOT NULL,
    "display_name" TEXT NOT NULL,
    "org_subtype" TEXT,
    "pan" TEXT,
    "cin" TEXT,
    "status" "OrgStatus" NOT NULL DEFAULT 'ACTIVE',
    "address" JSONB,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    "created_by" UUID,

    CONSTRAINT "organisations_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "users" (
    "id" UUID NOT NULL,
    "portal_type" "PortalType" NOT NULL,
    "email" CITEXT NOT NULL,
    "user_id_handle" TEXT,
    "name" TEXT NOT NULL,
    "mobile" TEXT,
    "password_hash" TEXT,
    "mfa_secret_enc" TEXT,
    "mfa_enabled" BOOLEAN NOT NULL DEFAULT false,
    "is_demo" BOOLEAN NOT NULL DEFAULT false,
    "status" "UserStatus" NOT NULL DEFAULT 'INVITED',
    "failed_logins" INTEGER NOT NULL DEFAULT 0,
    "locked_until" TIMESTAMPTZ(6),
    "last_login_at" TIMESTAMPTZ(6),
    "email_verified" BOOLEAN NOT NULL DEFAULT false,
    "muted_notification_types" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    "created_by" UUID,

    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "memberships" (
    "user_id" UUID NOT NULL,
    "organisation_id" UUID NOT NULL,
    "status" "MembershipStatus" NOT NULL DEFAULT 'ACTIVE',
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "memberships_pkey" PRIMARY KEY ("user_id","organisation_id")
);

-- CreateTable
CREATE TABLE "user_roles" (
    "user_id" UUID NOT NULL,
    "organisation_id" UUID NOT NULL,
    "role" "Role" NOT NULL,
    "granted_by" UUID,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "user_roles_pkey" PRIMARY KEY ("user_id","organisation_id","role")
);

-- CreateTable
CREATE TABLE "tender_assignments" (
    "tender_id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "role" "Role" NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" UUID,

    CONSTRAINT "tender_assignments_pkey" PRIMARY KEY ("tender_id","user_id","role")
);

-- CreateTable
CREATE TABLE "sessions" (
    "id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "organisation_id" UUID,
    "refresh_token_hash" TEXT NOT NULL,
    "mfa_verified" BOOLEAN NOT NULL DEFAULT false,
    "device" TEXT,
    "ip" TEXT,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "last_seen_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "expires_at" TIMESTAMPTZ(6) NOT NULL,
    "revoked_at" TIMESTAMPTZ(6),

    CONSTRAINT "sessions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "password_reset_tokens" (
    "id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "token_hash" TEXT NOT NULL,
    "expires_at" TIMESTAMPTZ(6) NOT NULL,
    "used_at" TIMESTAMPTZ(6),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "password_reset_tokens_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "invitations" (
    "id" UUID NOT NULL,
    "organisation_id" UUID NOT NULL,
    "email" CITEXT NOT NULL,
    "roles" "Role"[],
    "token_hash" TEXT NOT NULL,
    "invited_by" UUID NOT NULL,
    "expires_at" TIMESTAMPTZ(6) NOT NULL,
    "accepted_at" TIMESTAMPTZ(6),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "invitations_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "idempotency_keys" (
    "key" TEXT NOT NULL,
    "user_id" UUID NOT NULL,
    "route" TEXT NOT NULL,
    "request_hash" TEXT NOT NULL,
    "response_status" INTEGER NOT NULL,
    "response_body" JSONB NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "expires_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "idempotency_keys_pkey" PRIMARY KEY ("key")
);

-- CreateTable
CREATE TABLE "tenders" (
    "id" UUID NOT NULL,
    "code" TEXT NOT NULL,
    "organisation_id" UUID NOT NULL,
    "public_id" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "category" TEXT,
    "department" TEXT,
    "objective" TEXT,
    "procurement_mode" "ProcurementMode" NOT NULL DEFAULT 'SINGLE_ENVELOPE',
    "estimated_value" DECIMAL(20,2),
    "value_public" BOOLEAN NOT NULL DEFAULT false,
    "quantity" TEXT,
    "delivery_location" TEXT,
    "required_by" DATE,
    "bid_open_at" TIMESTAMPTZ(6),
    "bid_deadline" TIMESTAMPTZ(6),
    "tech_opening_at" TIMESTAMPTZ(6),
    "state" "TenderState" NOT NULL DEFAULT 'DRAFT',
    "current_version" INTEGER NOT NULL DEFAULT 1,
    "reference_date_policy" "ReferenceDatePolicy" NOT NULL DEFAULT 'BID_DEADLINE',
    "externally_published" BOOLEAN NOT NULL DEFAULT false,
    "flags" JSONB NOT NULL DEFAULT '{}',
    "public_fields" JSONB,
    "published_at" TIMESTAMPTZ(6),
    "cancelled_reason" TEXT,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    "created_by" UUID,

    CONSTRAINT "tenders_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "tender_versions" (
    "id" UUID NOT NULL,
    "tender_id" UUID NOT NULL,
    "version" INTEGER NOT NULL,
    "reason" "TenderVersionReason" NOT NULL,
    "corrigendum_id" UUID,
    "snapshot" JSONB NOT NULL,
    "created_by" UUID,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "tender_versions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "tender_documents" (
    "id" UUID NOT NULL,
    "tender_id" UUID NOT NULL,
    "tender_version" INTEGER NOT NULL,
    "document_id" UUID NOT NULL,
    "role" "TenderDocumentRole" NOT NULL,
    "is_public" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "tender_documents_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "tender_clauses" (
    "id" UUID NOT NULL,
    "tender_id" UUID NOT NULL,
    "tender_version" INTEGER NOT NULL,
    "document_id" UUID,
    "clause_ref" TEXT NOT NULL,
    "heading" TEXT,
    "text" TEXT NOT NULL,
    "page_start" INTEGER,
    "page_end" INTEGER,
    "bbox" JSONB,
    "category" TEXT,
    "is_requirement_candidate" BOOLEAN NOT NULL DEFAULT false,
    "segmentation_method" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "tender_clauses_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "requirements" (
    "id" UUID NOT NULL,
    "tender_id" UUID NOT NULL,
    "code" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "category" "RequirementCategory" NOT NULL,
    "mandatory" BOOLEAN NOT NULL DEFAULT false,
    "weight" DECIMAL(8,2) NOT NULL DEFAULT 0,
    "envelope" "Envelope" NOT NULL DEFAULT 'TECHNICAL',
    "source_clause_id" UUID,
    "status" "RequirementStatus" NOT NULL DEFAULT 'ACTIVE',
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "requirements_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "rules" (
    "id" UUID NOT NULL,
    "requirement_id" UUID NOT NULL,
    "tender_id" UUID NOT NULL,
    "code" TEXT NOT NULL,
    "current_version_id" UUID,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "rules_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "rule_versions" (
    "id" UUID NOT NULL,
    "rule_id" UUID NOT NULL,
    "version" INTEGER NOT NULL,
    "origin" "RuleOrigin" NOT NULL,
    "status" "RuleVersionStatus" NOT NULL,
    "dsl" JSONB,
    "plain_english" TEXT,
    "ambiguity_flags" JSONB NOT NULL DEFAULT '[]',
    "validation_errors" JSONB NOT NULL DEFAULT '[]',
    "llm_meta" JSONB,
    "edit_reason" TEXT,
    "approved_by" UUID,
    "approved_at" TIMESTAMPTZ(6),
    "rejected_reason" TEXT,
    "supersedes_id" UUID,
    "tender_version" INTEGER NOT NULL,
    "created_by" UUID,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "rule_versions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "corrigenda" (
    "id" UUID NOT NULL,
    "tender_id" UUID NOT NULL,
    "code" TEXT NOT NULL,
    "from_version" INTEGER NOT NULL,
    "to_version" INTEGER NOT NULL,
    "summary" TEXT NOT NULL,
    "changes" JSONB NOT NULL DEFAULT '[]',
    "impact" JSONB,
    "state" "CorrigendumState" NOT NULL DEFAULT 'DRAFT',
    "approved_by" UUID,
    "published_at" TIMESTAMPTZ(6),
    "created_by" UUID,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "corrigenda_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "clarifications_public" (
    "id" UUID NOT NULL,
    "tender_id" UUID NOT NULL,
    "question" TEXT NOT NULL,
    "answer" TEXT,
    "published_at" TIMESTAMPTZ(6),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "clarifications_public_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "bidder_profiles" (
    "organisation_id" UUID NOT NULL,
    "verification_level" INTEGER NOT NULL DEFAULT 0,
    "badge_status" TEXT NOT NULL DEFAULT 'NONE',
    "summary" JSONB NOT NULL DEFAULT '{}',
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "bidder_profiles_pkey" PRIMARY KEY ("organisation_id")
);

-- CreateTable
CREATE TABLE "authorised_persons" (
    "id" UUID NOT NULL,
    "organisation_id" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "designation" TEXT,
    "email" CITEXT,
    "mobile" TEXT,
    "authorisation_document_id" UUID,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "authorised_persons_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "directors" (
    "id" UUID NOT NULL,
    "organisation_id" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "din" TEXT,
    "source_document_id" UUID,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "directors_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "addresses" (
    "id" UUID NOT NULL,
    "organisation_id" UUID NOT NULL,
    "kind" TEXT NOT NULL,
    "raw" TEXT NOT NULL,
    "normalised" TEXT NOT NULL,
    "pin_code" TEXT,
    "hash" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "addresses_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "contacts" (
    "id" UUID NOT NULL,
    "organisation_id" UUID NOT NULL,
    "kind" TEXT NOT NULL,
    "value_normalised" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "contacts_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "vault_items" (
    "id" UUID NOT NULL,
    "organisation_id" UUID NOT NULL,
    "evidence_type" "DocType" NOT NULL,
    "document_id" UUID NOT NULL,
    "document_version" INTEGER NOT NULL,
    "status" "FreshnessState" NOT NULL DEFAULT 'FRESH',
    "valid_from" DATE,
    "valid_until" DATE,
    "freshness_policy" JSONB,
    "last_verified_at" TIMESTAMPTZ(6),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "vault_items_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "documents" (
    "id" UUID NOT NULL,
    "owner_org_id" UUID NOT NULL,
    "uploaded_by" UUID,
    "original_filename" TEXT NOT NULL,
    "mime" TEXT NOT NULL,
    "size_bytes" BIGINT NOT NULL,
    "sha256" TEXT NOT NULL,
    "storage_bucket" TEXT NOT NULL,
    "storage_key" TEXT NOT NULL,
    "page_count" INTEGER,
    "declared_type" "DocType",
    "doc_type" "DocType",
    "doc_type_confidence" DECIMAL(4,3),
    "classification_method" TEXT,
    "text_layer" "TextLayer",
    "processing_status" "DocumentProcessingStatus" NOT NULL DEFAULT 'UPLOADED',
    "quality" JSONB,
    "scan_status" "ScanStatus",
    "envelope" "Envelope" NOT NULL DEFAULT 'TECHNICAL',
    "version" INTEGER NOT NULL DEFAULT 1,
    "version_group_id" UUID NOT NULL,
    "supersedes_id" UUID,
    "qr_payloads" JSONB,
    "signature_info" JSONB,
    "failure_code" TEXT,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "documents_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "document_pages" (
    "id" UUID NOT NULL,
    "document_id" UUID NOT NULL,
    "page_no" INTEGER NOT NULL,
    "width" DECIMAL(10,2) NOT NULL,
    "height" DECIMAL(10,2) NOT NULL,
    "rotation" INTEGER NOT NULL DEFAULT 0,
    "text_source" "TextLayer" NOT NULL,
    "text" TEXT NOT NULL,
    "words" JSONB NOT NULL DEFAULT '[]',
    "ocr_confidence" DECIMAL(5,2),
    "image_key" TEXT,

    CONSTRAINT "document_pages_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "document_tables" (
    "id" UUID NOT NULL,
    "document_id" UUID NOT NULL,
    "page_no" INTEGER NOT NULL,
    "bbox" JSONB NOT NULL,
    "rows" JSONB NOT NULL,

    CONSTRAINT "document_tables_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "bids" (
    "id" UUID NOT NULL,
    "code" TEXT NOT NULL,
    "tender_id" UUID NOT NULL,
    "bidder_org_id" UUID NOT NULL,
    "state" "BidState" NOT NULL DEFAULT 'DRAFT',
    "tender_version_at_submission" INTEGER,
    "submitted_at" TIMESTAMPTZ(6),
    "submission_id" TEXT,
    "submitted_by" UUID,
    "declaration_accepted_at" TIMESTAMPTZ(6),
    "source" "BidSource" NOT NULL DEFAULT 'PORTAL',
    "current_bid_version" INTEGER NOT NULL DEFAULT 0,
    "withdrawn_reason" TEXT,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    "created_by" UUID,

    CONSTRAINT "bids_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "bid_versions" (
    "id" UUID NOT NULL,
    "bid_id" UUID NOT NULL,
    "version" INTEGER NOT NULL,
    "reason" "BidVersionReason" NOT NULL,
    "manifest" JSONB NOT NULL,
    "manifest_hash" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" UUID,

    CONSTRAINT "bid_versions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "bid_documents" (
    "bid_id" UUID NOT NULL,
    "bid_version" INTEGER NOT NULL,
    "document_id" UUID NOT NULL,
    "envelope" "Envelope" NOT NULL,
    "mapped_requirement_ids" UUID[] DEFAULT ARRAY[]::UUID[],

    CONSTRAINT "bid_documents_pkey" PRIMARY KEY ("bid_id","bid_version","document_id")
);

-- CreateTable
CREATE TABLE "financial_bids" (
    "id" UUID NOT NULL,
    "bid_id" UUID NOT NULL,
    "amount" DECIMAL(20,2),
    "currency" TEXT NOT NULL DEFAULT 'INR',
    "document_id" UUID,
    "sealed" BOOLEAN NOT NULL DEFAULT true,
    "opened_at" TIMESTAMPTZ(6),
    "opened_by" UUID,

    CONSTRAINT "financial_bids_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "extracted_fields" (
    "id" UUID NOT NULL,
    "document_id" UUID NOT NULL,
    "field" TEXT NOT NULL,
    "value_raw" TEXT NOT NULL,
    "value_normalised" JSONB,
    "unit" TEXT,
    "page_no" INTEGER NOT NULL,
    "bbox" JSONB,
    "confidence" DECIMAL(4,3) NOT NULL,
    "method" "ExtractionMethod" NOT NULL,
    "extractor_version" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "extracted_fields_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "claims" (
    "id" UUID NOT NULL,
    "subject_org_id" UUID NOT NULL,
    "bid_id" UUID,
    "claim_type" TEXT NOT NULL,
    "key" TEXT,
    "value" JSONB NOT NULL,
    "status" "ClaimStatus" NOT NULL DEFAULT 'FIELD_EXTRACTED',
    "verification_status" "ClaimStatus",
    "verification_method" TEXT,
    "verified_at" TIMESTAMPTZ(6),
    "valid_until" DATE,
    "freshness_state" "FreshnessState",
    "requirement_ids" UUID[] DEFAULT ARRAY[]::UUID[],
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "claims_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "evidence" (
    "id" UUID NOT NULL,
    "claim_id" UUID NOT NULL,
    "extracted_field_id" UUID,
    "document_id" UUID,
    "page_no" INTEGER,
    "bbox" JSONB,
    "excerpt" TEXT,
    "role" "EvidenceRole" NOT NULL DEFAULT 'SUPPORTS',
    "verification_result_id" UUID,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "evidence_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "reconciliation_results" (
    "id" UUID NOT NULL,
    "bid_id" UUID,
    "org_id" UUID,
    "field" TEXT NOT NULL,
    "outcome" "ReconciliationOutcome" NOT NULL,
    "values" JSONB NOT NULL,
    "method" TEXT NOT NULL,
    "details" JSONB,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "reconciliation_results_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "verification_sources" (
    "id" UUID NOT NULL,
    "code" "SourceCode" NOT NULL,
    "name" TEXT NOT NULL,
    "domain" TEXT,
    "method" "VerificationMethod" NOT NULL,
    "environment" TEXT NOT NULL,
    "enabled" BOOLEAN NOT NULL DEFAULT true,
    "capability_status" "CapabilityStatus" NOT NULL,
    "last_health_check_at" TIMESTAMPTZ(6),
    "last_health_result" JSONB,
    "credential_status" "CredentialStatus" NOT NULL DEFAULT 'MISSING',
    "config_enc" TEXT,
    "adapter_version" TEXT,
    "portal_url" TEXT,
    "instructions" TEXT,
    "notes" TEXT,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "verification_sources_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "verification_requests" (
    "id" UUID NOT NULL,
    "claim_id" UUID NOT NULL,
    "bid_id" UUID,
    "source_id" UUID NOT NULL,
    "route" "VerificationRoute" NOT NULL,
    "automation_state" "AutomationState" NOT NULL,
    "priority" INTEGER NOT NULL DEFAULT 3,
    "created_by" UUID,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "verification_requests_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "verification_tasks" (
    "id" UUID NOT NULL,
    "code" TEXT NOT NULL,
    "request_id" UUID NOT NULL,
    "assignee_id" UUID,
    "status" "VerificationTaskStatus" NOT NULL DEFAULT 'QUEUED',
    "attempts" INTEGER NOT NULL DEFAULT 0,
    "last_attempt_at" TIMESTAMPTZ(6),
    "due_at" TIMESTAMPTZ(6),
    "notes" TEXT,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "verification_tasks_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "verification_results" (
    "id" UUID NOT NULL,
    "request_id" UUID NOT NULL,
    "mode" "VerificationMethod" NOT NULL,
    "outcome" "VerificationOutcome" NOT NULL,
    "normalised" JSONB,
    "raw_response_key" TEXT,
    "raw_response_sha256" TEXT,
    "captured_document_id" UUID,
    "checked_at" TIMESTAMPTZ(6) NOT NULL,
    "checked_by" UUID,
    "valid_until" DATE,
    "is_simulated" BOOLEAN NOT NULL DEFAULT false,
    "trusted_chain" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "verification_results_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "compliance_runs" (
    "id" UUID NOT NULL,
    "code" TEXT NOT NULL,
    "tender_id" UUID NOT NULL,
    "bid_id" UUID NOT NULL,
    "bid_version" INTEGER NOT NULL,
    "tender_version" INTEGER NOT NULL,
    "rule_version_ids" UUID[],
    "evidence_snapshot_hash" TEXT,
    "verification_snapshot_hash" TEXT,
    "engine_version" TEXT,
    "reference_date" DATE NOT NULL,
    "status" "RunStatus" NOT NULL DEFAULT 'RUNNING',
    "started_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "finished_at" TIMESTAMPTZ(6),
    "triggered_by" UUID,
    "trigger_reason" "RunTrigger" NOT NULL,

    CONSTRAINT "compliance_runs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "requirement_results" (
    "id" UUID NOT NULL,
    "run_id" UUID NOT NULL,
    "requirement_id" UUID NOT NULL,
    "rule_version_id" UUID,
    "result" "ComplianceResult" NOT NULL,
    "mandatory" BOOLEAN NOT NULL,
    "weight" DECIMAL(8,2) NOT NULL,
    "earned_weight" DECIMAL(8,2) NOT NULL,
    "trace" JSONB NOT NULL,
    "explanation" TEXT,
    "evidence_ids" UUID[] DEFAULT ARRAY[]::UUID[],

    CONSTRAINT "requirement_results_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "scores" (
    "run_id" UUID NOT NULL,
    "total" DECIMAL(5,2) NOT NULL,
    "applicable_weight" DECIMAL(10,2) NOT NULL,
    "earned_weight" DECIMAL(10,2) NOT NULL,
    "max_achievable" DECIMAL(5,2) NOT NULL,
    "provisional" BOOLEAN NOT NULL,
    "breakdown" JSONB NOT NULL,

    CONSTRAINT "scores_pkey" PRIMARY KEY ("run_id")
);

-- CreateTable
CREATE TABLE "mandatory_gate_results" (
    "run_id" UUID NOT NULL,
    "passed_count" INTEGER NOT NULL,
    "failed_count" INTEGER NOT NULL,
    "pending_count" INTEGER NOT NULL,
    "status" "GateStatus" NOT NULL,

    CONSTRAINT "mandatory_gate_results_pkey" PRIMARY KEY ("run_id")
);

-- CreateTable
CREATE TABLE "risk_assessments" (
    "run_id" UUID NOT NULL,
    "level" "RiskLevel" NOT NULL,
    "signals" JSONB NOT NULL,

    CONSTRAINT "risk_assessments_pkey" PRIMARY KEY ("run_id")
);

-- CreateTable
CREATE TABLE "exceptions" (
    "id" UUID NOT NULL,
    "code" TEXT NOT NULL,
    "tender_id" UUID NOT NULL,
    "bid_id" UUID,
    "requirement_id" UUID,
    "category" "ExceptionCategory" NOT NULL,
    "severity" "RiskLevel" NOT NULL,
    "status" "ExceptionStatus" NOT NULL DEFAULT 'OPEN',
    "dedupe_key" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "detail" TEXT,
    "next_action" TEXT,
    "evidence_ids" UUID[] DEFAULT ARRAY[]::UUID[],
    "assigned_to" UUID,
    "resolution" TEXT,
    "resolved_by" UUID,
    "resolved_at" TIMESTAMPTZ(6),
    "source_run_id" UUID,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "exceptions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "exception_comments" (
    "id" UUID NOT NULL,
    "exception_id" UUID NOT NULL,
    "author_id" UUID NOT NULL,
    "body" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "exception_comments_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "overrides" (
    "id" UUID NOT NULL,
    "entity_type" TEXT NOT NULL,
    "entity_id" UUID NOT NULL,
    "original_value" JSONB NOT NULL,
    "new_value" JSONB NOT NULL,
    "reason" TEXT NOT NULL,
    "reference" TEXT,
    "actor_id" UUID NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "overrides_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "decisions" (
    "id" UUID NOT NULL,
    "tender_id" UUID NOT NULL,
    "bid_id" UUID NOT NULL,
    "run_id" UUID,
    "action" "DecisionAction" NOT NULL,
    "label" TEXT NOT NULL,
    "note" TEXT,
    "acknowledged_exception_ids" UUID[] DEFAULT ARRAY[]::UUID[],
    "actor_id" UUID NOT NULL,
    "role" "Role" NOT NULL,
    "idempotency_key" TEXT,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "decisions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "clarification_requests" (
    "id" UUID NOT NULL,
    "bid_id" UUID NOT NULL,
    "exception_id" UUID,
    "requirement_ids" UUID[] DEFAULT ARRAY[]::UUID[],
    "requested_by" UUID NOT NULL,
    "question" TEXT NOT NULL,
    "due_at" TIMESTAMPTZ(6) NOT NULL,
    "status" "ClarificationStatus" NOT NULL DEFAULT 'OPEN',
    "response_text" TEXT,
    "response_bid_version" INTEGER,
    "responded_at" TIMESTAMPTZ(6),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "clarification_requests_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "decision_label_configs" (
    "organisation_id" UUID NOT NULL,
    "action" "DecisionAction" NOT NULL,
    "label" TEXT NOT NULL,
    "requires_role" "Role" NOT NULL,

    CONSTRAINT "decision_label_configs_pkey" PRIMARY KEY ("organisation_id","action")
);

-- CreateTable
CREATE TABLE "audit_events" (
    "id" BIGSERIAL NOT NULL,
    "code" TEXT NOT NULL,
    "occurred_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "actor_id" UUID,
    "actor_role" TEXT,
    "actor_portal" TEXT,
    "organisation_id" UUID,
    "action" TEXT NOT NULL,
    "entity_type" TEXT NOT NULL,
    "entity_id" TEXT,
    "tender_id" UUID,
    "bid_id" UUID,
    "before" JSONB,
    "after" JSONB,
    "reason" TEXT,
    "evidence_refs" JSONB,
    "ip" TEXT,
    "session_id" UUID,
    "request_id" TEXT,
    "prev_hash" TEXT NOT NULL,
    "hash" TEXT NOT NULL,

    CONSTRAINT "audit_events_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "notifications" (
    "id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "type" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "body" TEXT NOT NULL,
    "link" TEXT,
    "critical" BOOLEAN NOT NULL DEFAULT false,
    "read_at" TIMESTAMPTZ(6),
    "emailed_at" TIMESTAMPTZ(6),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "notifications_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "jobs" (
    "id" UUID NOT NULL,
    "queue" TEXT NOT NULL,
    "entity_type" TEXT,
    "entity_id" TEXT,
    "status" "JobStatus" NOT NULL DEFAULT 'QUEUED',
    "step" TEXT,
    "attempts" INTEGER NOT NULL DEFAULT 0,
    "max_attempts" INTEGER NOT NULL DEFAULT 3,
    "started_at" TIMESTAMPTZ(6),
    "finished_at" TIMESTAMPTZ(6),
    "error_code" TEXT,
    "error_message" TEXT,
    "payload_hash" TEXT,
    "organisation_id" UUID,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "jobs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "feature_flags" (
    "key" TEXT NOT NULL,
    "enabled" BOOLEAN NOT NULL DEFAULT false,
    "scope" TEXT NOT NULL DEFAULT 'GLOBAL',
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "feature_flags_pkey" PRIMARY KEY ("key")
);

-- CreateTable
CREATE TABLE "system_settings" (
    "key" TEXT NOT NULL,
    "value" JSONB NOT NULL,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    "updated_by" UUID,

    CONSTRAINT "system_settings_pkey" PRIMARY KEY ("key")
);

-- CreateTable
CREATE TABLE "reports" (
    "id" UUID NOT NULL,
    "type" "ReportType" NOT NULL,
    "entity_id" UUID NOT NULL,
    "format" "ReportFormat" NOT NULL,
    "storage_bucket" TEXT,
    "storage_key" TEXT,
    "sha256" TEXT,
    "job_id" UUID,
    "organisation_id" UUID NOT NULL,
    "generated_by" UUID NOT NULL,
    "generated_at" TIMESTAMPTZ(6),
    "data_snapshot_hash" TEXT,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "reports_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "demo_requests" (
    "id" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "email" CITEXT NOT NULL,
    "organisation" TEXT,
    "message" TEXT,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "demo_requests_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "organisations_code_key" ON "organisations"("code");

-- CreateIndex
CREATE INDEX "organisations_type_idx" ON "organisations"("type");

-- CreateIndex
CREATE UNIQUE INDEX "users_email_key" ON "users"("email");

-- CreateIndex
CREATE UNIQUE INDEX "users_user_id_handle_key" ON "users"("user_id_handle");

-- CreateIndex
CREATE UNIQUE INDEX "sessions_refresh_token_hash_key" ON "sessions"("refresh_token_hash");

-- CreateIndex
CREATE INDEX "sessions_user_id_idx" ON "sessions"("user_id");

-- CreateIndex
CREATE UNIQUE INDEX "password_reset_tokens_token_hash_key" ON "password_reset_tokens"("token_hash");

-- CreateIndex
CREATE UNIQUE INDEX "invitations_token_hash_key" ON "invitations"("token_hash");

-- CreateIndex
CREATE UNIQUE INDEX "tenders_code_key" ON "tenders"("code");

-- CreateIndex
CREATE UNIQUE INDEX "tenders_public_id_key" ON "tenders"("public_id");

-- CreateIndex
CREATE INDEX "tenders_organisation_id_state_idx" ON "tenders"("organisation_id", "state");

-- CreateIndex
CREATE UNIQUE INDEX "tender_versions_tender_id_version_key" ON "tender_versions"("tender_id", "version");

-- CreateIndex
CREATE INDEX "tender_clauses_tender_id_tender_version_idx" ON "tender_clauses"("tender_id", "tender_version");

-- CreateIndex
CREATE UNIQUE INDEX "requirements_tender_id_code_key" ON "requirements"("tender_id", "code");

-- CreateIndex
CREATE UNIQUE INDEX "rules_tender_id_code_key" ON "rules"("tender_id", "code");

-- CreateIndex
CREATE UNIQUE INDEX "rule_versions_rule_id_version_key" ON "rule_versions"("rule_id", "version");

-- CreateIndex
CREATE UNIQUE INDEX "corrigenda_code_key" ON "corrigenda"("code");

-- CreateIndex
CREATE INDEX "directors_din_idx" ON "directors"("din");

-- CreateIndex
CREATE INDEX "addresses_hash_idx" ON "addresses"("hash");

-- CreateIndex
CREATE INDEX "contacts_value_normalised_idx" ON "contacts"("value_normalised");

-- CreateIndex
CREATE INDEX "documents_owner_org_id_sha256_idx" ON "documents"("owner_org_id", "sha256");

-- CreateIndex
CREATE UNIQUE INDEX "document_pages_document_id_page_no_key" ON "document_pages"("document_id", "page_no");

-- CreateIndex
CREATE UNIQUE INDEX "bids_code_key" ON "bids"("code");

-- CreateIndex
CREATE UNIQUE INDEX "bids_submission_id_key" ON "bids"("submission_id");

-- CreateIndex
CREATE UNIQUE INDEX "bids_tender_id_bidder_org_id_key" ON "bids"("tender_id", "bidder_org_id");

-- CreateIndex
CREATE UNIQUE INDEX "bid_versions_bid_id_version_key" ON "bid_versions"("bid_id", "version");

-- CreateIndex
CREATE UNIQUE INDEX "financial_bids_bid_id_key" ON "financial_bids"("bid_id");

-- CreateIndex
CREATE INDEX "extracted_fields_document_id_field_idx" ON "extracted_fields"("document_id", "field");

-- CreateIndex
CREATE INDEX "claims_bid_id_claim_type_idx" ON "claims"("bid_id", "claim_type");

-- CreateIndex
CREATE INDEX "claims_subject_org_id_claim_type_idx" ON "claims"("subject_org_id", "claim_type");

-- CreateIndex
CREATE INDEX "reconciliation_results_bid_id_field_idx" ON "reconciliation_results"("bid_id", "field");

-- CreateIndex
CREATE UNIQUE INDEX "verification_sources_code_key" ON "verification_sources"("code");

-- CreateIndex
CREATE UNIQUE INDEX "verification_tasks_code_key" ON "verification_tasks"("code");

-- CreateIndex
CREATE INDEX "verification_tasks_status_assignee_id_idx" ON "verification_tasks"("status", "assignee_id");

-- CreateIndex
CREATE UNIQUE INDEX "compliance_runs_code_key" ON "compliance_runs"("code");

-- CreateIndex
CREATE INDEX "compliance_runs_bid_id_started_at_idx" ON "compliance_runs"("bid_id", "started_at");

-- CreateIndex
CREATE UNIQUE INDEX "requirement_results_run_id_requirement_id_key" ON "requirement_results"("run_id", "requirement_id");

-- CreateIndex
CREATE UNIQUE INDEX "exceptions_code_key" ON "exceptions"("code");

-- CreateIndex
CREATE UNIQUE INDEX "exceptions_dedupe_key_key" ON "exceptions"("dedupe_key");

-- CreateIndex
CREATE INDEX "exceptions_tender_id_status_severity_idx" ON "exceptions"("tender_id", "status", "severity");

-- CreateIndex
CREATE INDEX "overrides_entity_type_entity_id_idx" ON "overrides"("entity_type", "entity_id");

-- CreateIndex
CREATE UNIQUE INDEX "decisions_idempotency_key_key" ON "decisions"("idempotency_key");

-- CreateIndex
CREATE UNIQUE INDEX "audit_events_code_key" ON "audit_events"("code");

-- CreateIndex
CREATE UNIQUE INDEX "audit_events_hash_key" ON "audit_events"("hash");

-- CreateIndex
CREATE INDEX "audit_events_entity_type_entity_id_idx" ON "audit_events"("entity_type", "entity_id");

-- CreateIndex
CREATE INDEX "audit_events_tender_id_occurred_at_idx" ON "audit_events"("tender_id", "occurred_at");

-- CreateIndex
CREATE INDEX "audit_events_actor_id_occurred_at_idx" ON "audit_events"("actor_id", "occurred_at");

-- CreateIndex
CREATE INDEX "notifications_user_id_read_at_idx" ON "notifications"("user_id", "read_at");

-- CreateIndex
CREATE INDEX "jobs_queue_status_idx" ON "jobs"("queue", "status");

-- AddForeignKey
ALTER TABLE "memberships" ADD CONSTRAINT "memberships_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "memberships" ADD CONSTRAINT "memberships_organisation_id_fkey" FOREIGN KEY ("organisation_id") REFERENCES "organisations"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "user_roles" ADD CONSTRAINT "user_roles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "user_roles" ADD CONSTRAINT "user_roles_organisation_id_fkey" FOREIGN KEY ("organisation_id") REFERENCES "organisations"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "tender_assignments" ADD CONSTRAINT "tender_assignments_tender_id_fkey" FOREIGN KEY ("tender_id") REFERENCES "tenders"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "tender_assignments" ADD CONSTRAINT "tender_assignments_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "sessions" ADD CONSTRAINT "sessions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "password_reset_tokens" ADD CONSTRAINT "password_reset_tokens_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "tenders" ADD CONSTRAINT "tenders_organisation_id_fkey" FOREIGN KEY ("organisation_id") REFERENCES "organisations"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "tender_versions" ADD CONSTRAINT "tender_versions_tender_id_fkey" FOREIGN KEY ("tender_id") REFERENCES "tenders"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "tender_documents" ADD CONSTRAINT "tender_documents_tender_id_fkey" FOREIGN KEY ("tender_id") REFERENCES "tenders"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "tender_documents" ADD CONSTRAINT "tender_documents_document_id_fkey" FOREIGN KEY ("document_id") REFERENCES "documents"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "tender_clauses" ADD CONSTRAINT "tender_clauses_tender_id_fkey" FOREIGN KEY ("tender_id") REFERENCES "tenders"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "requirements" ADD CONSTRAINT "requirements_tender_id_fkey" FOREIGN KEY ("tender_id") REFERENCES "tenders"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "requirements" ADD CONSTRAINT "requirements_source_clause_id_fkey" FOREIGN KEY ("source_clause_id") REFERENCES "tender_clauses"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "rules" ADD CONSTRAINT "rules_requirement_id_fkey" FOREIGN KEY ("requirement_id") REFERENCES "requirements"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "rules" ADD CONSTRAINT "rules_tender_id_fkey" FOREIGN KEY ("tender_id") REFERENCES "tenders"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "rule_versions" ADD CONSTRAINT "rule_versions_rule_id_fkey" FOREIGN KEY ("rule_id") REFERENCES "rules"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "corrigenda" ADD CONSTRAINT "corrigenda_tender_id_fkey" FOREIGN KEY ("tender_id") REFERENCES "tenders"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "clarifications_public" ADD CONSTRAINT "clarifications_public_tender_id_fkey" FOREIGN KEY ("tender_id") REFERENCES "tenders"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "bidder_profiles" ADD CONSTRAINT "bidder_profiles_organisation_id_fkey" FOREIGN KEY ("organisation_id") REFERENCES "organisations"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "authorised_persons" ADD CONSTRAINT "authorised_persons_organisation_id_fkey" FOREIGN KEY ("organisation_id") REFERENCES "organisations"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "directors" ADD CONSTRAINT "directors_organisation_id_fkey" FOREIGN KEY ("organisation_id") REFERENCES "organisations"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "addresses" ADD CONSTRAINT "addresses_organisation_id_fkey" FOREIGN KEY ("organisation_id") REFERENCES "organisations"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "contacts" ADD CONSTRAINT "contacts_organisation_id_fkey" FOREIGN KEY ("organisation_id") REFERENCES "organisations"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "vault_items" ADD CONSTRAINT "vault_items_organisation_id_fkey" FOREIGN KEY ("organisation_id") REFERENCES "organisations"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "vault_items" ADD CONSTRAINT "vault_items_document_id_fkey" FOREIGN KEY ("document_id") REFERENCES "documents"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "documents" ADD CONSTRAINT "documents_owner_org_id_fkey" FOREIGN KEY ("owner_org_id") REFERENCES "organisations"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "document_pages" ADD CONSTRAINT "document_pages_document_id_fkey" FOREIGN KEY ("document_id") REFERENCES "documents"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "document_tables" ADD CONSTRAINT "document_tables_document_id_fkey" FOREIGN KEY ("document_id") REFERENCES "documents"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "bids" ADD CONSTRAINT "bids_tender_id_fkey" FOREIGN KEY ("tender_id") REFERENCES "tenders"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "bids" ADD CONSTRAINT "bids_bidder_org_id_fkey" FOREIGN KEY ("bidder_org_id") REFERENCES "organisations"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "bid_versions" ADD CONSTRAINT "bid_versions_bid_id_fkey" FOREIGN KEY ("bid_id") REFERENCES "bids"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "bid_documents" ADD CONSTRAINT "bid_documents_bid_id_fkey" FOREIGN KEY ("bid_id") REFERENCES "bids"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "bid_documents" ADD CONSTRAINT "bid_documents_document_id_fkey" FOREIGN KEY ("document_id") REFERENCES "documents"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "financial_bids" ADD CONSTRAINT "financial_bids_bid_id_fkey" FOREIGN KEY ("bid_id") REFERENCES "bids"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "extracted_fields" ADD CONSTRAINT "extracted_fields_document_id_fkey" FOREIGN KEY ("document_id") REFERENCES "documents"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "claims" ADD CONSTRAINT "claims_subject_org_id_fkey" FOREIGN KEY ("subject_org_id") REFERENCES "organisations"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "claims" ADD CONSTRAINT "claims_bid_id_fkey" FOREIGN KEY ("bid_id") REFERENCES "bids"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "evidence" ADD CONSTRAINT "evidence_claim_id_fkey" FOREIGN KEY ("claim_id") REFERENCES "claims"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "evidence" ADD CONSTRAINT "evidence_extracted_field_id_fkey" FOREIGN KEY ("extracted_field_id") REFERENCES "extracted_fields"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "evidence" ADD CONSTRAINT "evidence_document_id_fkey" FOREIGN KEY ("document_id") REFERENCES "documents"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "evidence" ADD CONSTRAINT "evidence_verification_result_id_fkey" FOREIGN KEY ("verification_result_id") REFERENCES "verification_results"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "verification_requests" ADD CONSTRAINT "verification_requests_claim_id_fkey" FOREIGN KEY ("claim_id") REFERENCES "claims"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "verification_requests" ADD CONSTRAINT "verification_requests_source_id_fkey" FOREIGN KEY ("source_id") REFERENCES "verification_sources"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "verification_tasks" ADD CONSTRAINT "verification_tasks_request_id_fkey" FOREIGN KEY ("request_id") REFERENCES "verification_requests"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "verification_results" ADD CONSTRAINT "verification_results_request_id_fkey" FOREIGN KEY ("request_id") REFERENCES "verification_requests"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "compliance_runs" ADD CONSTRAINT "compliance_runs_tender_id_fkey" FOREIGN KEY ("tender_id") REFERENCES "tenders"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "compliance_runs" ADD CONSTRAINT "compliance_runs_bid_id_fkey" FOREIGN KEY ("bid_id") REFERENCES "bids"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "requirement_results" ADD CONSTRAINT "requirement_results_run_id_fkey" FOREIGN KEY ("run_id") REFERENCES "compliance_runs"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "requirement_results" ADD CONSTRAINT "requirement_results_requirement_id_fkey" FOREIGN KEY ("requirement_id") REFERENCES "requirements"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "scores" ADD CONSTRAINT "scores_run_id_fkey" FOREIGN KEY ("run_id") REFERENCES "compliance_runs"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "mandatory_gate_results" ADD CONSTRAINT "mandatory_gate_results_run_id_fkey" FOREIGN KEY ("run_id") REFERENCES "compliance_runs"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "risk_assessments" ADD CONSTRAINT "risk_assessments_run_id_fkey" FOREIGN KEY ("run_id") REFERENCES "compliance_runs"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "exceptions" ADD CONSTRAINT "exceptions_tender_id_fkey" FOREIGN KEY ("tender_id") REFERENCES "tenders"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "exceptions" ADD CONSTRAINT "exceptions_bid_id_fkey" FOREIGN KEY ("bid_id") REFERENCES "bids"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "exception_comments" ADD CONSTRAINT "exception_comments_exception_id_fkey" FOREIGN KEY ("exception_id") REFERENCES "exceptions"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "decisions" ADD CONSTRAINT "decisions_tender_id_fkey" FOREIGN KEY ("tender_id") REFERENCES "tenders"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "decisions" ADD CONSTRAINT "decisions_bid_id_fkey" FOREIGN KEY ("bid_id") REFERENCES "bids"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "clarification_requests" ADD CONSTRAINT "clarification_requests_bid_id_fkey" FOREIGN KEY ("bid_id") REFERENCES "bids"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "decision_label_configs" ADD CONSTRAINT "decision_label_configs_organisation_id_fkey" FOREIGN KEY ("organisation_id") REFERENCES "organisations"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
